### ISSUE TITLE
 does not work

### ISSUE THREAD

**Issue by powergt** [Crypter/MAChaser#1]
I tried the sketch with a wemos d1 (based on esp8266). it runs correctly but does not find any mac address. arp_find is always = -1

**Comment by Crypter** [comment]
I'll look into it, the Arduino ESP8266 SDK has been updated twice since I wrote this thing.

**Comment by Crypter** [comment]
I've just checked, the Arduino sketch still works as expected. You might not get all the entries on its first iteration, but it works. I'm too busy to do fine tuning at the moment to fix that.
Check if you are connected to a network, and check if you have "Client Isolation" enabled on your network. If you do - ping across clients might not work - hence, no devices found.
